
defaults:
  - priors/default
  - plasma/default
  - optimisation_info/emcee_test
  - data_info/exp
  - model_info/all_models
  - write_info/test
  - pulse_info/p11089


pulse_info:
  pulse_to_write: 43000000
  tstart: 0.12
  tend: 0.13
  diagnostics: [
      "cxff_tws_c",
      "xrcs",
  ]

  quant_to_optimise: [
      "cxff_tws_c.ti",
      "xrcs.raw_spectra"
  ]

optimisation_info:
  param_names: [ "ion_temperature.y0"
  ]
  pca_profiles: [ ]
  iterations: 40
  stopping_criteria_factor: 0.1

write_info:
  mds_write: True
  run: TEST
  best: False
  run_info: Test run
