
defaults:
  - model: xrcs
  - optimisation: emcee_test
  - plasma: default
  - priors: default
  - reader: mock
  - writer: test

pulse: null
tstart: 0.05
tend: 0.06
dt: 0.01

optimisation:
  iterations: 1000
  stopping_criteria_factor: 0.1