basic_prior_info:
  ion_temperature.y0: ["get_uniform", 1000, 10000]
  ion_temperature.y1: ["get_uniform", 50, 50.1]
  ion_temperature.wped: ["get_uniform", 1, 2]
  ion_temperature.wcenter: ["get_uniform", 0.2, 0.4]
  ion_temperature.peaking: ["get_uniform", 1, 10]

  electron_density.y0: ["get_uniform", 2e19, 2e20]
  electron_density.y1: ["get_uniform", 1e18, 1e19]
  electron_density.wped: ["loguniform", 2, 20]
  electron_density.wcenter: ["get_uniform", 0.2, 0.4]
  electron_density.peaking: ["get_uniform", 1, 4]

  electron_temperature.y0: ["get_uniform", 1000, 5000]
  electron_temperature.y1: ["get_uniform", 50, 50.1]
  electron_temperature.wped: ["get_uniform", 1, 10]
  electron_temperature.wcenter: ["get_uniform", 0.2, 0.4]
  electron_temperature.peaking: ["get_uniform", 1, 4]

  impurity_density:ar.y0: ["loguniform", 2e16, 1e18]
  impurity_density:ar.y1: ["loguniform", 1e16, 1.01e16]
  impurity_density:ar.wped: ["get_uniform", 1, 2]
  impurity_density:ar.wcenter: ["get_uniform", 0.2, 0.4]
  impurity_density:ar.peaking: ["get_uniform", 1, 4]

  neutral_density.y0: ["loguniform", 1e13, 1e15]
  neutral_density.y1: ["loguniform", 1e13, 1e16]
  neutral_density.wped: ["get_uniform", 16, 17]
  neutral_density.wcenter: ["get_uniform", 0.2, 0.4]
  neutral_density.peaking: ["get_uniform", 1, 6]

cond_prior_info:
    electron_temperature.y0/electron_temperature.y1: "greater_than"
    electron_density.y0/electron_density.y1: "greater_than"
    impurity_density:ar.y0/impurity_density:ar.y1: "greater_than"
    ion_temperature.y0/ion_temperature.y1: "greater_than"
