method: "bo"

param_names: ["ion_temperature.y0", ]
pca_profiles: []
pca_components: 2

n_calls: 2
n_initial_points: 1
noise: 1.0E-10
acq_func: "LCB"
xi: 0.20
kappa: 5
initial_point_generator: "lhs"
use_previous_best: False

boundary_samples: 1000
model_samples: 10
posterior_samples: 1000