method: "emcee"

param_names: ["ion_temperature.y0"]
pca_profiles: []
pca_components: 2

starting_samples: 20
iterations: 5
nwalkers: 8
stopping_criteria_factor: 0.5
sample_method: "random"
stopping_criteria: "mode"
burn_frac: 0.01
