profile_params:
  electron_density:
    y0: 5e19
    y1: 2e18
    yend: 1e18
    wped: 3
    wcenter: 0.3
    peaking: 1.2
  impurity_density:ar:
    y0: 1e17
    y1: 1e15
    yend: 1e15
    wcenter: 0.3
    wped: 3
    peaking: 2
  impurity_density:c:
    y0: 5e17
    y1: 2e17
    yend: 2e17
    wcenter: 0.3
    wped: 3
    peaking: 1.2
  impurity_density:he:
    y0: 5e17
    y1: 2e17
    yend: 2e17
    wcenter: 0.3
    wped: 3
    peaking: 1.2
  electron_temperature:
    y0: 3000
    y1: 50
    yend: 10
    wcenter: 0.2
    wped: 3
    peaking: 1.5
  ion_temperature:
    y0: 5000
    y1: 50
    yend: 10
    wcenter: 0.2
    wped: 3
    peaking: 1.5
  neutral_density:
    y0: 1e14
    y1: 5e15
    yend: 5e15
    wcenter: 0.01
    wped: 18
    peaking: 1
  toroidal_rotation:
    y0: 500.0e3
    y1: 10.0e3
    yend: 0.0
    peaking: 1.5
    wcenter: 0.35
    wped: 3

plasma_attrs: [
    "electron_temperature",
    "electron_density",
    "ion_temperature",
    "ion_density",
    "impurity_density",
    "fast_density",
    "pressure_fast",
    "neutral_density",
    "zeff",
    "meanz",
    "wp",
    "wth",
    "pressure_tot",
    "pressure_th",
]