
electron_density:
    y0: 5.0e+19
    y1: 5.0e+18
    yend: 2.0e+18
    peaking: 1.2
    wcenter: 0.3
    wped: 6


impurity_density:
    y0: 5.0e+16
    y1: 1.0e+15
    yend: 1.0e+15
    peaking: 3
    wcenter: 0.3
    wped: 6


neutral_density:
    y0: 1.0e+13
    y1: 1.0e+15
    yend: 1.0e+15
    peaking: 20
    wcenter: 0.0
    wped: 18


electron_temperature:
    y0: 3.0e+3
    y1: 50
    yend: 5
    peaking: 1.5
    wcenter: 0.25
    wped: 3


ion_temperature:
    y0: 5.0e+3
    y1: 50
    yend: 10
    peaking: 1.5
    wcenter: 0.25
    wped: 3


toroidal_rotation:
    y0: 500.0e+3
    y1: 10.0e+3
    yend: 0.0
    peaking: 0.3
    wcenter: 0.25
    wped: 3
