phantom: True
mock: False
set_ts: True
apply_rshift: True
profile_params_to_update: {}

filter_coords:
  cxff_pi:
    ti: [ "channel", [ 3, 5 ] ]
    vtor: [ "channel", [ 3, 5 ] ]
  cxff_tws_c:
    ti: [ "channel", [ 1, 2 ] ]
    vtor: [ "channel", [ 1, 2 ] ]

diagnostics: [
            "xrcs",
            "cxff_pi",
            "ts", ]

quant_to_optimise: [
                    "xrcs.intens",
                    "cxff_pi.ti",
                    "ts.ne",
                    "ts.te"]

equilibrium: efit
